### ISSUE TITLE
REQUEST: Unity3D Plugin

### ISSUE THREAD

**Issue by kdzapp** [y-fujii/ovrvnc#4]
Hello,

I've built an app in Unity and I'd love to use this library as a Unity asset. I was wondering if I could go about it by making a JAR and using that as a plugin with Unity? 

https://docs.unity3d.com/Manual/AndroidJARPlugins.html

If not, what else would you recommend? I have a simple VNC implementation that's the c# vnc library, but the performance is horrible, would much rather use this.

Thanks!

**Comment by kdzapp** [comment]
Just following up:

https://docs.unity3d.com/Manual/AndroidAARPlugins.html

That might even be better

**Comment by y-fujii** [comment]
I think it would be better to use [TigerVNC](https://github.com/TigerVNC/tigervnc) directly.
ovrvnc uses TigerVNC as a VNC library.  Although it is not officially released as a library, its backend code is well-separated from the frontend.
`ovrvnc/src/vnc_thread.hpp` might be helpful.

**Comment by kdzapp** [comment]
Thanks! I will try using their java implementation directly
