### ISSUE TITLE
doesn't work on Oculus Quest

### ISSUE THREAD

**Issue by assadollahi** [y-fujii/ovrvnc#5]
installed it on the Oculus Quest, toml file is minimal containing the IP address of the Raspberry Pi, I want to log in to. Pi is on the same network, VNC login from PC on the same network works.
When starting on the Quest (from "unknown sources"),  screen stays black.

Update: modified the toml file to include background color in light grey and that works. So the toml file is being read and processed, it seems. Would be helpful if the program would display an error message.

**Comment by TheJoeSchr** [comment]
Works for me on Quest2 

My screen stayed black until I configured the .toml as well

**Comment by TheJoeSchr** [comment]
ok, I spoke to soon. What works is mouse pointer and seeing the screen. Sadly no transfer of keyboard input from oculus quest (via a connected usb keyboard to oculus 2)

**Comment by assadollahi** [comment]
seems to be a "won't fix". sad.

**Comment by WilsonBradley** [comment]
To bad there is no more development on this. This had a lot of potential considering Samsung Dex, Linux deploy, etc and other on side powerful portable computers (Raspberry Pi) this could have utilized.
